name: WebdriverIO Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}
      TESULTS_TOKEN: ${{ secrets.TESULTS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run WebdriverIO tests
        run: npm run wdio

      # Optional: Generate and upload Allure Report
      - name: Generate Allure report
        if: always()
        run: |
          npm install -g allure-commandline
          if [ -d "allure-results" ]; then
            allure generate allure-results --clean -o allure-report
          else
            echo "allure-results directory not found"
            exit 1
          fi

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set up git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Check out the gh-pages branch
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          
          # Clear the gh-pages branch content
          rm -rf ./*
          
          # Copy the Allure report to the gh-pages branch
          cp -R ../allure-report/* .
          
          # Commit and push the report to the gh-pages branch
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages
